name: Publish App
on:
  workflow_dispatch:

permissions:
  contents: read
env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ vars.SEMVER }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITRELEASEMANAGERALLACCESS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: |
            3.1.x

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v0
        with:
          versionSpec: "0.10.x"
          preferLatestVersion: true

      - name: Display Semver
        shell: bash
        run: |
          echo ${{env.SEMVER}}

      - uses: gittools/actions/gitreleasemanager/publish@v0
        name: Publish release with GitReleaseManager
        with:
          token: ${{ secrets.GITRELEASEMANAGERALLACCESS }}
          owner: "md-owes"
          repository: "directory-deleter"
          tagName: "${{env.SEMVER}}"
