name: Release App
on:
  workflow_run:
    workflows: ["WindowsBuid" , "MacBuild"]
    branches: [main]
    types: [completed]
permissions:
  contents: read
env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  release-artifacts:
    name: Release Artifacts
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ vars.SEMVER }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITRELEASEMANAGERALLACCESS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: | 
            3.1.x

      - uses: ahmadnassri/action-workflow-run-wait@v1

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v0
        with:
          versionSpec: "0.10.x"
          preferLatestVersion: true

      - name: Display Semver
        shell: bash
        run: |
          echo ${{env.SEMVER}}

      - name: Restore Mac PKG Cache
        uses: actions/cache/restore@v3
        id: mac-cache
        with:
          path: | 
            bin/publish/pkg/directory-deleter-v${{env.SEMVER}}.pkg
          enableCrossOsArchive: true
          key: directory-deleter-mac-pkg-v${{env.SEMVER}}

      - name: Restore Win EXE Cache
        uses: actions/cache/restore@v3
        id: winexe-cache
        with:
          path: "**/*.exe.zip"
          enableCrossOsArchive: true
          key: directory-deleter-win-exe-v${{env.SEMVER}}

      - name: Restore Win MSI Cache
        uses: actions/cache/restore@v3
        id: winmsi-cache
        with:
          path: "**/*.msi.zip"
          enableCrossOsArchive: true
          key: directory-deleter-win-exe-v${{env.SEMVER}}

      - name: Create git tag
        run: |
          git remote remove origin
          git remote add origin https://${{ secrets.GITRELEASEMANAGERALLACCESS }}@github.com/md-owes/directory-deleter
          git tag ${{env.SEMVER}}
          git push origin ${{env.SEMVER}}

      - name: Create release with GitReleaseManager
        uses: gittools/actions/gitreleasemanager/create@v0.10.2
        with:
          token: ${{ secrets.GITRELEASEMANAGERALLACCESS }}
          owner: "md-owes"
          repository: "directory-deleter"
          milestone: ${{env.SEMVER}}
          name: "${{env.SEMVER}}"
          assets: |
            directory-deleter-v${{env.SEMVER}}.msix.zip
            directory-deleter-v${{env.SEMVER}}.exe.zip
            directory-deleter-v${{env.SEMVER}}.pkg.zip
